name = "amp-example-rust"
version = "0.0.3"
authors = ["Eguo Wang <wangeguo@gmail.com>"]
description = "A simple Rust example app using Rocket"
readme = "README.md"
homepage = "https://github.com/amphitheatre-app/amp-example-rust"
repository = "https://github.com/amphitheatre-app/amp-example-rust"
license = "Apache-2.0"
license-file = "LICENSE"
keywords = ["example", "rust", "getting-started"]
categories = ["example"]

[build]
builder = "wangeguo/amp-default-cluster-builder"

[build.env]
CNB_PLATFORM_API = "0.9"
